[package]
name = "vshymanskyy/wasm3"
version = "0.5.0"
description = "🚀 The fastest WebAssembly interpreter. You can finally run WebAssembly on WebAssembly 😆"
readme = "README.md"
repository = "https://github.com/wasm3/wasm3"
homepage = "https://github.com/wasm3/wasm3"

[[module]]
name = "wasm3"
source = "build/wasm3-wasi.wasm"
abi = "wasi"

[[module]]
name = "wasm3-strace"
source = "build/wasm3-strace.wasm"
abi = "wasi"

[[command]]
name = "wasm3"
module = "wasm3"

[[command]]
name = "wasm3-strace"
module = "wasm3-strace"
